language: ruby
rvm:
  - "1.9.3"
install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install linux-headers-$(uname -r)
  - sudo apt-get -y install virtualbox-4.2
  - VBoxManage -v
  - gem query --local
  - gem install vagrant --version 1.0.6
  - gem query --local
  - gem uninstall json --version 1.5.4 --ignore-dependencies
  - gem query --local
  - gem install json --version 1.7.6
  - gem query --local
  - gem install veewee
  - gem query --local
script:
  - date
  - veewee vbox build 'ubuntu-11.10-server-i386' --auto --debug --nogui
  - date
  - export VEEWEEBOT_DEPLOY_FILE=ubuntu-11.10-server-i386.box
  - curl https://raw.github.com/veewee-community/veeweebot/master/deploy.sh > deploy.sh
  - chmod +x deploy.sh
  - ./deploy.sh
env:
  global:
    - secure: "NkHH5RTqsxd+yHTNE2KhOkzhLHg9oh2UCeyvvnUWhYcwTCpRv+IrXc6Fi7uJ\n9FGe1DuSD/cnhNFJSMDbL5mN6NSSZ1HM6U2YPvsZBuBsJcePJr1rlDdbdmwQ\nJMssMIxdr4qRMvjjRX2fjXICx8MKA2w0jEKLbTzVbIjDopzE07I="
    - secure: "XYFSnPbrczz5LLSAYzCHQCFpZZF6e7Ofwu+bVnSDezqmXoCqbzBvuc6JL1AB\nP5IifPOum7crZ4DP6ybb9jxiIvkafP9Al/QpOON4rZOFUc7K8yYDRVoQLHoL\noak/VtLPHU4DjSguxVaR3A8ddap1a8jjGRZ1KGGwFxG9UqNo7A0="
